INSERT INTO MEDIA (NAME, MEDIA_TYPE) VALUES ('NHL Advanced', 'BOOK');
INSERT INTO BOOK (ID) VALUES (1);
INSERT INTO AUTHOR (NAME) VALUES ('Kurt Sauer');
INSERT INTO BOOK_AUTHOR (BOOK_ID, AUTHOR_ID) VALUES (1,1);